DROP DATABASE IF EXISTS AUTHDB;

CREATE DATABASE AUTHDB
  CHARSET = 'utf8'
  COLLATE = 'utf8_general_ci';

-- USERS --

CREATE TABLE AUTHDB.USERS
(
  ID          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME        VARCHAR(128)    NOT NULL UNIQUE,
  PASSWORD	  VARCHAR(128)    NOT NULL,
  ROLE		  VARCHAR(10) NOT NULL
);